### ISSUE TITLE
Writing standard style tag in html rather than using dropzone.style() method

### ISSUE THREAD

**Issue by Yuxiaoy1** [greyli/flask-dropzone#50]
Compare the following two writing styles of customizing the style for dropzone area: 

```css
<style>
.dropzone {
    border: 2px dashed #0087F7;
    margin: 10%;
    min-height: 400px;
}
</style>
```

```py
{{ dropzone.style('border: 2px dashed #0087F7; margin: 10%; min-height: 400px;') }}
```

The first one (standard style tag) has two pros:
- more readable and maintainable, while the second one looks sort of ugly.
- more flexible on customizing different styles for multiple dropzones on one page, just replacing `.dropzone` to `#<dropzone-id>`, while the second one cannot realize.

Thus, I think the `dropzone.style()` method is unnecessary, and I suggest writing the standard style tag for customizing the style.

What do you think?
